apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-config
  namespace: ecommerce
  labels:
    app: payment
    app.kubernetes.io/name: payment
    app.kubernetes.io/component: backend
data:
  ENVIRONMENT: "production"
  LOG_LEVEL: "info"
  PAYMENT_HTTP_PORT: "8005"
  PAYMENT_GRPC_PORT: "9005"
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "ecommerce"
  POSTGRES_SSL_MODE: "disable"
  PAYMENT_DB_NAME: "payment_db"
  KAFKA_BROKERS: "kafka:9092"
  PAYMENT_GATEWAY: "stripe"
