apiVersion: v1
kind: ConfigMap
metadata:
  name: search-config
  namespace: ecommerce
  labels:
    app: search
    app.kubernetes.io/name: search
    app.kubernetes.io/component: backend
data:
  ENVIRONMENT: "production"
  LOG_LEVEL: "info"
  SEARCH_HTTP_PORT: "8010"
  SEARCH_GRPC_PORT: "9010"
  KAFKA_BROKERS: "kafka:9092"
  ELASTICSEARCH_URL: "http://elasticsearch:9200"
  SEARCH_ENGINE: "elasticsearch"
  PRODUCT_SERVICE_URL: "http://product:8001"
