apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-config
  namespace: ecommerce
  labels:
    app: inventory
    app.kubernetes.io/name: inventory
    app.kubernetes.io/component: backend
data:
  ENVIRONMENT: "production"
  LOG_LEVEL: "info"
  INVENTORY_HTTP_PORT: "8007"
  INVENTORY_GRPC_PORT: "9007"
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "ecommerce"
  POSTGRES_SSL_MODE: "disable"
  INVENTORY_DB_NAME: "inventory_db"
  KAFKA_BROKERS: "kafka:9092"
  RESERVATION_TTL_SECONDS: "900"
