apiVersion: v1
kind: Service
metadata:
  name: inventory
  namespace: ecommerce
  labels:
    app: inventory
    app.kubernetes.io/name: inventory
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    app: inventory
  ports:
    - name: http
      port: 8007
      targetPort: 8007
      protocol: TCP
    - name: grpc
      port: 9007
      targetPort: 9007
      protocol: TCP
