apiVersion: v1
kind: ConfigMap
metadata:
  name: media-config
  namespace: ecommerce
  labels:
    app: media
    app.kubernetes.io/name: media
    app.kubernetes.io/component: backend
data:
  ENVIRONMENT: "production"
  LOG_LEVEL: "info"
  MEDIA_HTTP_PORT: "8011"
  MEDIA_GRPC_PORT: "9011"
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "ecommerce"
  POSTGRES_SSL_MODE: "disable"
  MEDIA_DB_NAME: "media_db"
  KAFKA_BROKERS: "kafka:9092"
  MINIO_ENDPOINT: "minio:9000"
  MINIO_BUCKET: "ecommerce-media"
  MINIO_USE_SSL: "false"
  MEDIA_BASE_URL: "https://media.ecommercego.dev"
