apiVersion: v1
kind: Service
metadata:
  name: media
  namespace: ecommerce
  labels:
    app: media
    app.kubernetes.io/name: media
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    app: media
  ports:
    - name: http
      port: 8011
      targetPort: 8011
      protocol: TCP
    - name: grpc
      port: 9011
      targetPort: 9011
      protocol: TCP
