apiVersion: v1
kind: ConfigMap
metadata:
  name: cart-config
  namespace: ecommerce
  labels:
    app: cart
    app.kubernetes.io/name: cart
    app.kubernetes.io/component: backend
data:
  ENVIRONMENT: "production"
  LOG_LEVEL: "info"
  CART_HTTP_PORT: "8002"
  REDIS_ADDR: "redis:6379"
  REDIS_DB: "0"
  CART_TTL_HOURS: "168"
  KAFKA_BROKERS: "kafka:9092"
