apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-config
  namespace: ecommerce
  labels:
    app: notification
    app.kubernetes.io/name: notification
    app.kubernetes.io/component: backend
data:
  ENVIRONMENT: "production"
  LOG_LEVEL: "info"
  NOTIFICATION_HTTP_PORT: "8009"
  NOTIFICATION_GRPC_PORT: "9009"
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "ecommerce"
  POSTGRES_SSL_MODE: "disable"
  NOTIFICATION_DB_NAME: "notification_db"
  KAFKA_BROKERS: "kafka:9092"
  SMTP_HOST: "smtp.ecommercego.dev"
  SMTP_PORT: "587"
  SMTP_FROM: "noreply@ecommercego.dev"
