apiVersion: v1
kind: ConfigMap
metadata:
  name: campaign-config
  namespace: ecommerce
  labels:
    app: campaign
    app.kubernetes.io/name: campaign
    app.kubernetes.io/component: backend
data:
  ENVIRONMENT: "production"
  LOG_LEVEL: "info"
  CAMPAIGN_HTTP_PORT: "8008"
  CAMPAIGN_GRPC_PORT: "9008"
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "ecommerce"
  POSTGRES_SSL_MODE: "disable"
  CAMPAIGN_DB_NAME: "campaign_db"
  KAFKA_BROKERS: "kafka:9092"
